### ISSUE TITLE
Facet API haiku

### ISSUE THREAD

**Issue by pcambra** [stevector/plugin-haikus#2]
TBD

**Comment by pcambra** [comment]
widgets and filters seem to be the best concepts to explore here:
http://drupal.org/project/facetapi_slider
http://drupal.org/project/facetapi_bonus

url processor too:
http://drupal.org/project/facetapi_pretty_paths

Dependencies:
http://drupal.org/project/facetapi_bonus

**Comment by pcambra** [comment]
Haiku proposal

Search pages are to be
more rich and interesting.
Just... one... more... Facet...

**Comment by stevector** [comment]
Syllables don't line up. How about

Make your search pages
more rich and interesting
Just... one... more... facet.

**Comment by pcambra** [comment]
Thanks :)
